gcloud:
  project: intellifi-project
  location: us-east1
  base_url: https://intellifi-tgcmkbtxxq-ue.a.run.app
  tasks:
    queue: intellifi-events-queue
    service_account_email: 489767445099-compute@developer.gserviceaccount.com
default_encoding: UTF-8
emerge:
  secret_key: emerge_authorization
