gcloud:
  project: intellifi-project
  location: us-east1
  base_url: https://intellifi-tgcmkbtxxq-ue.a.run.app
  tasks:
    queue: intellifi-events-queue
    service_account_email: 489767445099-compute@developer.gserviceaccount.com
default_encoding: UTF-8
emerge:
  environment: prod
  firestore:
    collection: emerge_sync
    auth_document: auth
    access_token:
      location: access_token_prod
pandadoc:
  api_key_secret:
    location: pandadoc_api_key
    version: latest
hubspot:
  client_id: 24b7488c-4d57-42c0-8a57-d7e41af9f9e1
  client_secret:
    location: hubspot_client_secret
    version: latest
  firestore:
    collection: hubspot_sync
    auth_document: auth
    access_token:
      location: access_token
    expires_at:
      location: expires_at
    refresh_token:
      location: refresh_token
